### ISSUE TITLE
How to use in awslambda env?

### ISSUE THREAD

**Issue by sirvon** [Doerge/awslambda-pycrypto#1]
how can I use this package to avoid the problems associated with pycrypto in aws' lambda python 2.7 env?

thanks!

**Comment by hajdbo** [comment]
AWS Lambda python does not provide pycrypto, so if you need it:
- clone this repo
- add the file (including .pyc) to your lambda zip file, along with your custom lambda function
- upload the zip to AWS Lambda

**Comment by Doerge** [comment]
I'm sure you either solved it or moved on, but I've now added a README in bdab5f75547d73c60bf3d40d092c10d86930d214 to help others.
