### ISSUE TITLE
How to create aws packages from other similar libraries?

### ISSUE THREAD

**Issue by tmilicic** [Doerge/awslambda-pycrypto#2]
Hi don't know how to reach you other way. Thank you for posting this repo, it is really helpful :) I am wandering if you could share the method of creating this compiled version of package? I need to do the same stuff but with some other libraries.

**Comment by Doerge** [comment]
As far as I remember I just statically compiled it on an Amazon Linux EC2 node, then copied it out. Does that help?

**Comment by tmilicic** [comment]
Yeah, I tried that but somehow the EC2 node didn't want to install the library with pip....anyways I have just run virtualenv on my laptop that runs linux, installed everything and copied packages. Sorry for confusion.

**Comment by Doerge** [comment]
No probs.
